### ISSUE TITLE
ReferenceId not set with parcel

### ISSUE THREAD

**Issue by DaniWinter** [myparcelnl/sdk#123]
I can create parcels and see them in the MyParcel dashboard. The reference however is always empty.

**Comment by Mark-H** [comment]
`$consignment->setLabelDescription('Foo Bar')`

I don't know the difference with `$consignment->setReferenceId`, but it does seem to work. :)

**Comment by RichardPerdaan** [comment]
Dear @DaniWinter ,
Could you confirm if this problem is still going on, or is it already solved?

**Comment by DaniWinter** [comment]
Thank you, it works!
