### ISSUE TITLE
fatal error when exception thrown

### ISSUE THREAD

**Issue by hikashop-nicolas** [myparcelnl/sdk#145]
When MyParcel SDK throws exceptions I'm getting fatal errors.

![Error_ 0 Class 'MyParcelNL_Sdk_src_Exception_AddressException' not found - Google Chrome 2019-07-26 15 21 44](https://user-images.githubusercontent.com/6094338/61955276-edce2a00-afba-11e9-8e08-50d7cd4e81cc.png)

I checked the autoload.php file and I see that most other files are required there. If I add the exception files there, then I get the errors properly thrown and I can catch them.
So, either they should be added to the autoload.php or I'm doing something wrong that I don't understand.

**Comment by Mark-H** [comment]
Same problem here. It looks like the code uses PSR-0/PSR-4 style naming conventions, so perhaps a standard (composer) autoloader could be implemented?

Adding the files to `src/AutoLoader.php` does help.

**Comment by RichardPerdaan** [comment]
Thank you for reporting.
I adjusted it in version [2.1.3](https://github.com/myparcelnl/sdk/releases/tag/v2.1.3) (e9429361776baee5a2e9596532b74075b0d9318e).
