### ISSUE TITLE
setItemValue issue

### ISSUE THREAD

**Issue by hikashop-nicolas** [myparcelnl/sdk#151]
The readme indicates:
```
 ->setItemValue(["amount" => 200, "currency" => "EUR"]) // Must be array with amount and currency like in the example
```
However, in the class MyParcelCustomsItem, the $item_value parameter is cast to an integer:
```
    public function setItemValue($item_value)
    {
        $this->item_value = (int) $item_value;

        return $this;
    }
```
And the function encodeCdCountryItem which calls getItemValue also expects the returned value to always be an amount and not an array.
So there is some discrepency here. The way it is currently coded in the SDK, it also makes it impossible to provide item value in another currency than EUR.

**Comment by RichardPerdaan** [comment]
I have solved the discrepancy in a new version. This is solved from version [2.1.4.](https://github.com/myparcelnl/sdk/releases/tag/v2.1.4)

Unfortunately MyParcel only supports the currency `EUR`. This makes it impossible to adjust it in the SDK.

As soon as it is possible for MyParcel, this functionality will also be built into the SDK.
