### ISSUE TITLE
setLatestData() does not work with multiple consignments

### ISSUE THREAD

**Issue by Cornelis21** [myparcelnl/sdk#17]
Example code:

```
$parcels = ["refference_1", "refference_2"];

$myParcelCollection = new MyParcelCollection();

foreach($parcels as $parcel){
	$consignment = (new MyParcelConsignmentRepository())
		->setApiKey("API_KEY_HERE")
		->setReferenceId($parcel);

	$myParcelCollection->addConsignment($consignment);	
}
		
$myParcelCollection->setLatestData();
```
This throws the following error:
`Fatal error: Call to a member function apiDecode() on null`

Changing 
`$parcels = ["refference_1", "refference_2"];` 
to 
`parcels = ["refference_1"];`
eliminates the problem.

You could also move `$myParcelCollection->setLatestData();` to inside the `foreach` loop, but then obviously only the first parcel has the correct data.

Is there something wrong with my implementation or is this a bug in the SDK?

**Comment by reindert-vetter** [comment]
Thank you for your comment. I've fixed this in version 1.1.9:
https://github.com/myparcelnl/sdk/releases/tag/v1.1.9
