### ISSUE TITLE
Update composer file

### ISSUE THREAD

**Issue by dam-man** [myparcelnl/sdk#18]
HI

I can't install the SDK because I am running a PHP version which is too high.. 
Now: < 7.1 and newer versions aren't accepted. 
I am running PHP 7.1.6

Best Regards,
Robert

**Comment by dam-man** [comment]
When using composer (most of us wants that) then you get V0.1.0 which is not corresponding to the documentation. The code is working well on PHP 7.1.6 also :+1:

**Comment by reindert-vetter** [comment]
If you do the following, do you get the latest version?
```composer require myparcelnl/sdk "~1.1"```

**Comment by reindert-vetter** [comment]
I have done a pull request from your fork. The adjustment is present in version 1.1.10:
https://github.com/myparcelnl/sdk/releases/tag/v1.1.10

**Comment by dam-man** [comment]
Great! I will test and let you know.
Can I speak Dutch also?

**Comment by dam-man** [comment]
Issue has been fixed.

**Comment by reindert-vetter** [comment]
Oke, perfect dat het de oplossing was. Bedankt voor het testen!

**Comment by dam-man** [comment]
:+1:
