### ISSUE TITLE
->getBarcode() is null

### ISSUE THREAD

**Issue by JBtje** [myparcelnl/sdk#181]
In v2 I was able to get the Barcode from the initial created variable `$consignment`.
However, the same code in v3 does no longer work.

```php
$consignment = (new PostNLConsignment())
    ...
    ->setApiKey( config( 'parcel.myparcel.key' ) );

$MyParcelCollection = (new MyParcelCollection())->addConsignment( $consignment )
                          ->setPdfOfLabels();

$barcode = $consignment->getBarcode()
// barcode = NULL (fails)
```

However, using $MyParcelCollection, does allow me to get the barcode:

```php
// Get the barcode
$barcode = $MyParcelCollection->first()->getBarcode();
// barcode = 3SMYPA000000000 (works)
```

My assumption is that the pointer between `$consignment` and the one stored in the collection, somehow gets broken.
Not that important, but would be nice if it can be fixed.

**Comment by reindert-vetter** [comment]
This has indeed been changed in version 3. We had to make it immutable because a concignment can be copied. This is because we now need to support multi colo.
