### ISSUE TITLE
Class 'MyParcelNL\Sdk\src\Helper\TrackTraceUrl' not found

### ISSUE THREAD

**Issue by Roywcm** [myparcelnl/sdk#187]
Hi,

When I try 

```
$consignment = (new \MyParcelNL\Sdk\src\Model\Consignment\PostNLConsignment());
echo $consignment->getBarcodeUrl(3SMYPA123456789, '2231JE', 'NL');
```

I get 

```
Class 'MyParcelNL\Sdk\src\Helper\TrackTraceUrl' not found
```
Is this a bug? Or do I do something wrong?

**Comment by RichardPerdaan** [comment]
Hi @Roywcm ,

Thank you for reporting the problem you are currently facing.
Which version of the SDK are you using?

**Comment by Roywcm** [comment]
Version 3.1

**Comment by RichardPerdaan** [comment]
Hi @Roywcm 

Thank you for submitting the version number, I will look into the problem.

**Comment by Roywcm** [comment]
Hi @RichardPerdaan, any updates on this issue?

**Comment by badbitnl** [comment]
I'm facing exactly the same issue

**Comment by reindert-vetter** [comment]
Sorry for our late response, but this was resolved on February 26.
https://github.com/myparcelnl/sdk/pull/211
