### ISSUE TITLE
setPhone(string $phone) param null is given

### ISSUE THREAD

**Issue by JeniaPlakhotnyk** [myparcelnl/sdk#190]
setPhone(string $phone) param null is given because of strict types of input params on line 1058
Solution presented here
    /**
     * The address phone
     * Required: no
     *
     * @param string|null $phone
     *
     * @return $this
     */
    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

**Comment by RichardPerdaan** [comment]
Problem fixed in version [v3.1.4-beta.1](https://github.com/myparcelnl/sdk/releases/tag/v3.1.4-beta.1)
