### ISSUE TITLE
Backwards compatibility break with Laravel 5.5 LTS

### ISSUE THREAD

**Issue by rsmeding-troublefree** [myparcelnl/sdk#228]
Hi,

I just started integrating this package into our existing application. Unfortunately, we still use Laravel 5.5, and #217 seems to have broken compatibility with this version:

`[ErrorException]
  Declaration of MyParcelNL\Sdk\src\Support\Collection::push(...$values) should be compatible with Illuminate\Support
  \Collection::push($value)
`

I realize 5.5 is pretty old, but looking at 6.0, the push method has the same prototype as in 5.5, so I suspect the problem occurs there as well.

**Comment by rsmeding-troublefree** [comment]
Ah, I've just noticed the remark on version 4:

> If you use Laravel 6 or lower, use SDK version 3.x

It might be useful to also point this out in the README, since if you follow the instructions there, you never end up seeing it.

In addition, it might be useful to indicate this in composer.json using a [conflict rule](https://getcomposer.org/doc/04-schema.md#conflict).

**Comment by reindert-vetter** [comment]
You're right. We need to fix that soon. But I think it might be even better if we don't automatically extend the Laravel collections anymore. @rsmeding-troublefree (and others) what do you think?

**Comment by jasperpoppe** [comment]
Any update on this?

**Comment by rsmeding-troublefree** [comment]
@reindert-vetter Not extending the Laravel collections would be fine by me -- I don't really use the functionality it provides anyway.
