### ISSUE TITLE
Postbus setconsignment

### ISSUE THREAD

**Issue by NabilChennoufi** [myparcelnl/sdk#229]
`->setApiKey('mijnapikey')
                                        ->setReferenceId("$order_id")
                                        ->setCountry('NL')
                                        ->setPerson("$naam")
                                        ->setFullStreet("$adres")
                                        ->setPostalCode("$postcode")
                                        ->setCity("$plaats")
                                        ->setEmail("$email")
                                        ->setPackageType(2);
`
Hoe voeg ik een postbus toe voor de belgische bezoekers en een PostNL abroad package type

**Comment by RichardPerdaan** [comment]
Beste @NabilChennoufi ,

Het was even uitzoeken maar ik heb een oplossing gevonden.
Doordat je gebruik maakt van de setFullStreet zal er via de SDK gekeken worden of het adres in de juiste format staat.

Nu is het zo dat je bij een postbus het postbusnummer als huisnummer mag gebruiken. Als straat zal je dan Postbus krijgen.
Het zal er dan als volgt uitzien:

``` 
    'street' => 'Postbus',
    'number' => 12345,
    'postal_code' => '2965AG',
```

Doordat de setFullStreet kijkt of de straat en huisnummer goed is ingevuld, werkt het niet goed samen. Het huisnummer mag namelijk maximaal 4 characters bevatten.

Wanneer er een postbus in het adres staat, kan je het beste setStreet() en setNumber() gebruiken in plaats van setFullStreet():

``` 
    ->setStreet('Postbus')
    ->setNumber('12345')
```


In onze [api documentatie](https://myparcelnl.github.io/api/#package_type) is te lezen welke package types wij ondersteunen. Als je een EU zending of een wereld zending aanmaakt dat zijn er maar twee package_types mogelijk namelijk package_type 1 en 3 (Package en letter)

Voor nu sluit is ik de issue, mochten er nog vragen zijn dan is het mogelijk om de issue gewoon weer te openen

**Comment by NabilChennoufi** [comment]
Ik heb zojuist de code toegepast, maar nu heb ik een ander probleem. Namelijk dat ik de setStreet en setNumber worden ingenomen door de postbus. Nu kan ik de straatnaam en straatnummer niet er bij toevoegen omdat het is ingenomen.

**Comment by RichardPerdaan** [comment]
Beste @NabilChennoufi ,

Als je een order probeert aan te maken met een postbus, dan hoef je geen straatnaam en huisnummer in te vullen. 

Je heb dus 2 scenario's die je kan gebruiken om het pakket bij het juiste adres te laten bezorgen:

- Je gebruikt straatnaam en huisnummer, zonder gegevens van de postbus
- Je gebruikt gegevens van de postbus, zonder straatnaam en huisnummer

Ik heb van mijn product owner begrepen dat PostNL met allebei de scenario's goed om kan gaan en dat het pakket goed geleverd zal worden.

**Comment by NabilChennoufi** [comment]
Hallo Richard,

Hartelijk dank voor je bericht en je uitleg. Ik wist niet dat het proces van PostNL zo gaat. Nu weet ik het gelukkig wel en kan ik doorgaan met mijn project.

Met vriendelijke groeten,

Nabil

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
