### ISSUE TITLE
PickupPoints missing some fields

### ISSUE THREAD

**Issue by sharkooon** [myparcelnl/sdk#26]
cannot set the following fields for pickup points:
- location_code
- retail_network_id
- pickup country?

**Comment by reindert-vetter** [comment]
We currently do not support post office locations in Belgium via the SDK. We expect to support this within 3 weeks. You can also make a fork and create a pull request to add these 2 fields. You can use the API documentation:
https://myparcelnl.github.io/api/

**Comment by RichardPerdaan** [comment]
Since November 2018 it is possible to enter this data for a Belgian shipment. I will close the issue. If there are any questions I would like to hear from you.
