### ISSUE TITLE
Download link PDF gaat fout

### ISSUE THREAD

**Issue by sharkooon** [myparcelnl/sdk#268]
Aan deze documentatie zie ik dat er wat gewijzigd is mbt download link van labels pdf.
Required request headers: "Accept: application/json; charset=utf8"
Echter werkt dit nu niet voor labels minder dan 25 stuks. Ik krijg in de request een pdf terug ipv de pdf link.

**Comment by reindert-vetter** [comment]
@sharkooon Bedankt voor het melden van het probleem. Het probleem is nu opgelost.
