### ISSUE TITLE
SDK can't split Street + Housenumber + Suffix

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/sdk#294]
In Magento2 the default fields allow a full address to be filled into one field. However the SDK isn't able to split this address.

<img width="519" alt="Checkout 2021-02-23 15-20-39" src="https://user-images.githubusercontent.com/54140671/108856831-bedec680-75ea-11eb-90f8-c6813e7ec045.png">

**Comment by RichardPerdaan** [comment]
fixed in [v7.2.0](https://github.com/myparcelnl/sdk/releases/tag/v7.2.0)
