### ISSUE TITLE
Labels printen voor DPD zending lukt niet (via Woocommerce plugin)

### ISSUE THREAD

**Issue by blaatpraat** [myparcelnl/sdk#303]
Als je vanuit Woocommerce via de MyParcel plugin een label voor een DPD zending wilt afdrukken, lukt dit niet.
Na troubleshooting blijkt het een fout te zijn in de SDK, daarom log ik het in dit project.

Een DPD zending wordt standaard altijd met 500 verzekering aangeboden (er is geen mogelijkheid om dit uit te schakelen, althans niet voor zendingen vanuit België).

Bestand: myparcelnl/sdk/src/Model/Consignment/DPDConsignment.php

Regel 27 stelt dat verzekering altijd 0 euro moet zijn:
`public const INSURANCE_POSSIBILITIES_LOCAL = [0];`
Op deze constraint faalt het printen van een label.
Bij het wijzigen naar het volgende lukt het wel:
`public const INSURANCE_POSSIBILITIES_LOCAL = [0, 500];`

**Comment by EdieLemoine** [comment]
Hoi @blaatpraat, is dit nog steeds van toepassing?

**Comment by blaatpraat** [comment]
Dag @EdieLemoine, ondertussen niet meer zo te zien.

Ik verstuur bitter weinig met DPD, vooral PostNL, dus een hoge nood was er niet voor mij, dus ik printte deze tot nu toe steeds manueel af.
Maar ik kan bevestigen dat het dus werkt met de huidige versie van de SDK.

**Comment by EdieLemoine** [comment]
@blaatpraat goed om te horen, dankjewel :)
