### ISSUE TITLE
Missing support for PakjeGemak Pickup shipments

### ISSUE THREAD

**Issue by LeonidasJP** [myparcelnl/sdk#4]
Currently, it seems to be impossible to set the Pickup information for PakjeGemak shipments through the SDK. Is there already a planning to implement PakjeGemak support through the SDK?

**Comment by reindert-vetter** [comment]
That's right. The SDK is still in beta stage. You can not send a request with a PostNL location yet. Also, it is not possible to create a shipment outside the EU. I'll see if I can make today or Wednesday a concept for you. 

For your information: I'm from Thursday for a week on vacation.

**Comment by reindert-vetter** [comment]
In the latest version, it is possible to create a postcode location with the sdk
