### ISSUE TITLE
SplitStreet not working

### ISSUE THREAD

**Issue by janssenr** [myparcelnl/sdk#65]
SplitStreet is not working for the following address:
Bankastraat 23 - II

**Comment by RichardPerdaan** [comment]
Thank you for your message, I have this issue labeled as Feature. As soon as we working on it, you will hear from me.

**Comment by reindert-vetter** [comment]
Dear Jansen. Do you often have customers divide house number and addition by a space, a midline and another space? It is common for it to be separated only by a midline.

I close this issue. If you are still bothered by this, I would like to hear it and then have to find a solution.
