### ISSUE TITLE
street_additional_info can not be set

### ISSUE THREAD

**Issue by frankverhoeven** [myparcelnl/sdk#66]
There is no setter method for `street_additional_info`.

Also, if the additional info is included within the streetname (`streetname."\n".info`) and the additional info + streetname length does not exceed `MAX_STREET_LENTH`; it will be included in the streetname. This causes it to be displayed twice on the label (after the streetname (even without a space between the streetname and the additional info) and below the streetname).

**Comment by EdieLemoine** [comment]
`street_additional_info` getter and setter added in [v.1.4.0](https://github.com/myparcelnl/sdk/releases/tag/v1.4.0)

The other issue is fixed in [v.1.5.0](https://github.com/myparcelnl/sdk/releases/tag/v1.5.0)
