### ISSUE TITLE
Support cooled_delivery

### ISSUE THREAD

**Issue by frankverhoeven** [myparcelnl/sdk#82]
The `cooled_delivery` [option](https://myparcelnl.github.io/api/#7_C_1) is currently not supported.

**Comment by nitinsbuzz** [comment]
We need this option

**Comment by RichardPerdaan** [comment]
Hi @frankverhoeven and @nitinsbuzz ,

Today I was told that we will remove these functionalities from our API. As a result, it will no longer possible for us to support this in the SDK. A similar solution is `Return` the package to the sender when the recipient is not home.

You can use this by using `->isReturn(),`

I also close the issue, if there are any questions please let me know.
